// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4awk7yJdq0W8UBevOgPcmJQ6tP8Lol3o',
    appId: '1:523851281455:android:e02ebccf3a2c175b3f82da',
    messagingSenderId: '523851281455',
    projectId: 'slsd-capstone-project',
    databaseURL: 'https://slsd-capstone-project-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'slsd-capstone-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFvsBy0jehao1p7rUuZLAUcrfhqaU4oUc',
    appId: '1:523851281455:ios:92207592ed5cd6053f82da',
    messagingSenderId: '523851281455',
    projectId: 'slsd-capstone-project',
    databaseURL: 'https://slsd-capstone-project-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'slsd-capstone-project.appspot.com',
    androidClientId: '523851281455-qv1r7bi17befchfic32qta4fh3vuo41p.apps.googleusercontent.com',
    iosClientId: '523851281455-h8q4v4nnso00nqf1p8qakd38pa2qr9oc.apps.googleusercontent.com',
    iosBundleId: 'com.example.testProject',
  );
}
