// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhxltRG8ojvVdhmXSo_-8EsH1c415ZnxY',
    appId: '1:999650887394:web:452cff36a4fc96286b80bb',
    messagingSenderId: '999650887394',
    projectId: 'slsd-firebase-test',
    authDomain: 'slsd-firebase-test.firebaseapp.com',
    storageBucket: 'slsd-firebase-test.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTMjRb9oSfkemSNv60gsbynwSk_l1uJag',
    appId: '1:999650887394:android:c51d4b26684ed0bf6b80bb',
    messagingSenderId: '999650887394',
    projectId: 'slsd-firebase-test',
    storageBucket: 'slsd-firebase-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCC3o39jX_qdcWF1sbpkXj5C6G646CPwAA',
    appId: '1:999650887394:ios:1d957f64d09641c86b80bb',
    messagingSenderId: '999650887394',
    projectId: 'slsd-firebase-test',
    storageBucket: 'slsd-firebase-test.appspot.com',
    iosClientId: '999650887394-pvuk1t3jd7p5vui26cc9ckd2l1djsg6l.apps.googleusercontent.com',
    iosBundleId: 'com.example.testProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCC3o39jX_qdcWF1sbpkXj5C6G646CPwAA',
    appId: '1:999650887394:ios:1d957f64d09641c86b80bb',
    messagingSenderId: '999650887394',
    projectId: 'slsd-firebase-test',
    storageBucket: 'slsd-firebase-test.appspot.com',
    iosClientId: '999650887394-pvuk1t3jd7p5vui26cc9ckd2l1djsg6l.apps.googleusercontent.com',
    iosBundleId: 'com.example.testProject',
  );
}
